title: Jinchen Ge
logo: /assets/img/logo.png
cv: /assets/docs/CV.pdf
description: AI engineer from Graphcore
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
linkedin: https://www.linkedin.com/in/jinchen-ge-884784139/
